import { Injectable } from "@angular/core";

@Injectable({providedIn: 'root'})


export class DenialService{

    private denials: any = [
        {pr: '', co: 'CO', code: 18, reason: 'Duplicate', subreason1:'', subreason2:'', desc: 'If whole claim denied as a duplicate, first check prior dates of service to determine if there are two encounters for the same date of service. If two encounters are found, verify all claim details, including the rendering provider, CPT code, charge amount, diagnosis code, patient name, and rendering provider. If the claim is an exact duplicate, it can be adjusted accordingly. If no such information is found in prior dates of service, call the insurance company and ask for the status of the original claim. Once you receive the original claim status, follow the appropriate workflow.', desc2:'If two CPT codes were billed on the same claim and one was paid while the other was denied as a duplicate, check the medical records to confirm if the services were indeed performed twice. For example, if X-ray CPT 72010 was billed twice, with one paid and the other denied, review the medical records. If two X-ray reports are found with different timings, verify the rendering provider for both X-rays. If the rendering provider is the same, append Modifier 76 to the claim to indicate that the same service was performed twice by the same provider. If the rendering providers are different, append Modifier 77 to indicate that the same service was performed by different providers. This should help get the claim paid.', noteTool: 'Not Available', audio: 'audio/CO-18_Duplicate_.ogg', audio2: ''},
        {pr: '', co: 'CO', code: 24, reason: 'Capitation', subreason1:'', subreason2:'', desc: 'Capitation is a contract between a provider and a payer in which the payer pays a fixed amount in advance for a particular patient for a whole month. This amount is called the capitation amount, and the month-long period is the capitation period. When handling this type of denial, first check whether the rendering provider on the claim is a PCP or a specialist. If the provider is a specialist, call the insurance company and request them to reprocess the claim, as capitation costs do not apply to specialists. If the rendering provider is a PCP, check the capitation period. If the date of service falls within the capitation period, escalate the issue to the client. If the date of service is outside the capitation period, request the insurance company to reprocess the claim.', desc2:'', noteTool: 'Not Available', audio: 'audio/CO-24_Capitation_.ogg', audio2: ''},
        {pr: '', co: 'CO', code: 50, reason: 'Not Medical Necessity', subreason1:'Commercial', subreason2:'Medicare', desc: 'If you receive a denial from a commercial payer for a specific CPT code, the first step is to call the insurance company to determine why the CPT code was denied, particularly if it’s due to medical necessity. Once you have this information, ask the representative which documents are needed to prove medical necessity. Typically, you can submit two key documents: medical records and a medical necessity statement. Providing these documents should help in getting the claim paid.', desc2: 'For Medicare denials, the process involves following Local Coverage Determination (LCD) guidelines. Start by obtaining the LCD number for the denied CPT code from the CMS.gov website. Search for the CPT code on the LCD search function to retrieve the LCD number. Then, review the LCD guidelines to identify the appropriate diagnosis codes that support the CPT code. Compare these to the diagnosis codes billed on your claim. If they do not align with the LCD guidelines, escalate the issue to the coding department. If the claim adheres to the guidelines, call the Medicare reopening line, explain the situation to the representative, and request reprocessing of the claim.', noteTool: 'Not Availalbe', audio: "audio/CO-50_Medically_Not_Necessity_(Commercial)_.ogg", audio2: 'audio/CO-50_Medically_Not_Necessity_(Medicare)_.ogg'},
        {pr: 'PR', co: '', code: 51, reason: 'Pre-existence Condition', subreason1:'', subreason2:'', desc: 'First of all we have to call the  insurance and ask them what is "Pre existence condition" patient has in his plan then we have to verify the services which was billed on the claim its related to that "Pre existence condition" or not , If its related then we have to check what is the waiting period, If the Date of service lies within the waiting period then bill it to patient , If Date of service lies out side of waiting period we can reprocess the claim.', desc2:'', noteTool: 'Not Availalbe', audio: "audio/CO-51_Per-existing.ogg", audio2: ''},
        {pr: 'PR', co: 'CO', code: 96, reason: 'Non Covered Services', subreason1:'CO-96', subreason2:'PR-96', desc: 'If the denial code is CO 96, it means the service is non-covered as per the provider contract, For CO 96, first check prior dates of service to see if payment was received for the same patient from the same payer for the same provider. If this information is found, call the insurance company, reference this claim, and request reprocessing. If no such information is found in prior dates of service, ask the insurance company why the CPT code is non-covered as per the provider contract. Once verified, escalate the issue to the client for write-off approval.', desc2:'For PR 96 denials, similarly check prior dates of service to see if payment was received from the same patient for the same CPT code from the same payer. If found, reference this claim when calling the insurance company and request reprocessing. If no prior information is found, call the insurance company to confirm if the CPT code is truly non-covered under the patient’s plan. If it is confirmed to be non-covered, proceed to bill the patient directly.', noteTool: 'Not Available', audio: 'audio/CO-96_Non_Covered_.ogg', audio2: 'audio/PR-96_Non_Covered_.ogg'},
        {pr: '', co: 'CO', code: 97, reason: 'Inclusive/Global to Surgery', subreason1:'Inclusive', subreason2:'Global to Surgery', desc: 'For an Example : If 2 CPT was billed on the claim , first is ENM services 99213,  2nd is surgery CPT 68510  in this senerio ENM services got denied  as inclusive with surgery CPT so we have to check  validate the same by using encoder pro if we found any conflict between this 2 CPT  so we can append Modifier 25 to ENM services and we can get our claim paid , If the situation is vice-versa instead of ENM services surgery CPT got denied as inclusive and we validate the same by using Encoder pro and we found conflict between this 2 CPT  so we can append modifier 59 to surgery CPT and we can get our claim paid.', desc2:'First, call the insurance company to determine which surgery CPT the claim is considered global to. Once identified, check the global period for that surgery CPT. If the date of service falls within the global period, append Modifier 57 to the E/M services if the diagnosis codes are the same. If the diagnosis codes are different, append Modifier 24 to the E/M services. For the surgery CPT, use Modifier 58 for planned services, Modifier 78 for unplanned services related to the original procedure, and Modifier 79 for unrelated services performed by the same physician during the post-operative period. Note that Modifiers 58, 78, and 79 should only be appended to surgery CPT codes.', noteTool: 'Not Available', audio: 'audio/CO-97_Inclusive.ogg', audio2: 'audio/CO-97_Globle_to_Surgery.ogg'},
        {pr: '', co: 'CO', code: 119, reason: 'Maximum benefits exhausted', subreason1:'Visit Limit', subreason2:'Dollar Value', desc: 'When addressing a denial related to "Maximum Benefits Exhausted" from an insurance company, it\'s crucial to clarify whether it\'s in terms of dollar value or visit limits. If the insurance representative states that the maximum benefits are exhausted in terms of visit limits, inquire about how many annual visits are allowed for the patient and verify how many visits have already been utilized, including the current claim. If the patient has exceeded the visit limit (e.g., visiting for the third time), ask the representative for details on when the second visit occurred and validate this against your records. Once confirmed, proceed with billing the patient.', desc2:'When addressing a denial related to "Maximum Benefits Exhausted" from an insurance company, it\'s crucial to clarify whether it\'s in terms of dollar value or visit limits. If the insurance representative states that the maximum benefits are exhausted in terms of dollar value, inquire about the total dollar amount allowed for the patient and verify how much of this amount has already been utilized, including the current claim. If the patient has exceeded the dollar limit (e.g., reaching the maximum allowed amount for the service), ask the representative for details on the previous claims and validate this against your records. Once confirmed, proceed with billing the patient.', noteTool: 'Not Available', audio: 'audio/CO-119_Maximum_Benefit_Met.ogg', audio2: 'audio/CO-199_Dollor_Value_.ogg'},
        {pr: '', co: 'CO', code: 197, reason: 'Authorization', subreason1:'', subreason2:'', desc: 'Authorization is require for the higher dollar value services like surgery and Arcilary services. If we recieved a denied of "No authorization CO 197" First of all we have to check what is the place of service which was billed on the claim. If its 23 which indicates emergency services and emergency services doesn\'t require the  authorization. We can call the insurance and them to reprocess it. If the "Place of service" 21 or 22 then we have to check whether we submited the claim with the Authorization number or not. For that reason we have to check claim form box number 23 our software and document management medical records. If we found the Authorization number then we have to validate the same by calling the insurance representative . If its valid good to go we can reprocess the claim. If its not valid we can ask for the hospital info. Is there any hospital claim associated with the same data service for the same patient. If yes then we have to cross verify whether that hospital claim is paid with the Authorization number or not. If yes then we have to verify whether that hospital authorization number valid for this claim or not. If its valid we can rebill the claim with that If its not valid we can ask for the "Retro auth" If we are in "Timely filing limit" to obtain a "Retro Auth" so we can rebill the claim with the "Retro Auth" If we are not getting "Retro Auth"   at that moment as per our process we are tasking to the client either we can  curtisy appeal with the "Medical Records".', desc2:'', noteTool: 'Not Available', audio: 'audio/CO-197_Authorization.ogg', audio2: ''},
        // {pr: '', co: '', code: NaN, reason: '', subreason1:'', subreason2:'', desc: '', desc2:'', noteTool: 'Not Available', audio: '', audio2: ''},
    ]

    getDenialsData(){
        return this.denials.slice();
    }
}